spring:
  application:
    name: user

server:
  port: 8888

say-hello:
  ribbon:
    eureka:
      enabled: false
    listOfServers: say-hello:8090
    # listOfServers: localhost:8090,localhost:8091
    ServerListRefreshInterval: 15000