server:
  port: 8899

feign:
  hystrix:
    enabled: false

  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

say-hello:
  ribbon:
    eureka:
      enabled: false
    listOfServers: say-hello:8090
    ServerListRefreshInterval: 15000
