version: '2.1'
services:
  say-hello:
    build: say-hello
    image: nhatthai/say-hello
    ports:
      - 8090:8090

  user:
    build: user
    image: nhatthai/user
    ports:
      - 8888:8888

  user-client-service:
    build: user-client-service
    image: nhatthai/user-client-service
    ports:
      - 8899:8899
    links:
      - "say-hello"