---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: user
        image: nhatthai/user:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: native
        - name: VERSION
          value: 'K8S_TIMESTAMP'
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: NodePort
  ports:
  # the port that this service should serve on
  - port: 8888
    targetPort: 8888
    nodePort: 31888
  selector:
    app: user
